import { PlacementDrive, JobApplication, StudentRecord, NotificationItem, ApplicationStatus, User, UserRole } from '../types';
import { studentService } from './studentService';
import { emitDataChange } from './dataEvents';
import { apiClient } from './apiClient';

type Actor=Pick<User,'id'|'name'|'email'|'role'>;
export type ActionResult={success:boolean;message:string};
export interface PlacementStats{totalStudents:number;totalDrives:number;publishedDrives:number;activeDrives:number;totalApplications:number;shortlisted:number;selected:number;byStatus:Record<ApplicationStatus,number>;byCompany:{company:string;applications:number;selected:number}[]}
const MANAGERS:UserRole[]=['tnp'];

class PlacementService {
  private drives:PlacementDrive[]=[];
  private applications:JobApplication[]=[];
  private notifications:NotificationItem[]=[];
  public async load():Promise<void>{try{[this.drives,this.applications,this.notifications]=await Promise.all([apiClient.drives(),apiClient.applications(),apiClient.notifications()]);emitDataChange();}catch{this.drives=[];this.applications=[];this.notifications=[];}}
  private canManage(actor?:Actor){return !!actor&&MANAGERS.includes(actor.role);}
  private denied():ActionResult{return{success:false,message:'Permission denied: only the T&P Officer or Admin can manage placement data.'};}
  public getAllDrives(){return this.drives;}
  public getPublishedDrives(){return this.drives.filter(d=>d.published&&(d.status||'Active')!=='Closed');}
  public getDriveById(id:string){return this.drives.find(d=>d.id===id)||null;}
  public createDrive(drive:Omit<PlacementDrive,'id'>,actor?:Actor){if(!this.canManage(actor))return null;const now=new Date().toISOString();const d:any={...drive,id:`drive-${Date.now()}`,status:drive.status||'Active',createdAt:now,publishedAt:drive.published?now:undefined};this.drives.unshift(d);emitDataChange();void apiClient.createDrive(d).then(saved=>{const i=this.drives.findIndex(x=>x.id===d.id);if(i>=0)this.drives[i]=saved;emitDataChange();}).catch(()=>{});return d;}
  public updateDrive(id:string,patch:Partial<PlacementDrive>,actor?:Actor){if(!this.canManage(actor))return false;const d=this.getDriveById(id);if(!d)return false;Object.assign(d,patch);if(d.published&&!d.publishedAt)d.publishedAt=new Date().toISOString();emitDataChange();void apiClient.updateDrive(id,patch).then(saved=>{const i=this.drives.findIndex(x=>x.id===id);if(i>=0)this.drives[i]=saved;emitDataChange();}).catch(()=>{});return true;}
  public setPublished(id:string,published:boolean,actor?:Actor){return this.updateDrive(id,{published},actor);}
  public deleteDrive(id:string,actor?:Actor){if(!this.canManage(actor))return false;if(!this.getDriveById(id))return false;this.drives=this.drives.filter(d=>d.id!==id);this.applications=this.applications.filter(a=>a.driveId!==id);emitDataChange();void apiClient.deleteDrive(id).then(()=>this.load()).catch(()=>{});return true;}
  public clearAll(){this.drives=[];this.applications=[];this.notifications=[];emitDataChange();}
  public checkEligibility(student:StudentRecord,drive:PlacementDrive){const reasons:string[]=[];const e=drive.eligibility;if(student.CGPA<e.minCGPA)reasons.push(`CGPA (${student.CGPA.toFixed(2)}) is below required minimum ${e.minCGPA}`);if(student.Backlogs>e.maxBacklogs)reasons.push(`Student has ${student.Backlogs} active backlogs (maximum permitted: ${e.maxBacklogs})`);const norm=(v:string)=>(v||'').trim().toLowerCase();if(e.allowedBranches?.length&&!e.allowedBranches.some(b=>norm(b)===norm(student.Branch)))reasons.push(`Branch '${student.Branch||'not set'}' is not in the approved branches list`);if(e.graduationYear&&student.Graduation_Year!==e.graduationYear)reasons.push(`Graduation year ${student.Graduation_Year||'not set'} does not match required batch ${e.graduationYear}`);return{eligible:reasons.length===0,reasons};}
  public isDeadlinePassed(drive:PlacementDrive){if(!drive.applicationDeadline)return false;const end=new Date(`${drive.applicationDeadline}T23:59:59`);return!isNaN(end.getTime())&&end.getTime()<Date.now();}
  public getDrivesForStudent(student:StudentRecord){return this.getPublishedDrives().map(d=>({drive:d,...this.checkEligibility(student,d)}));}
  public getAllApplications(){return this.applications;}
  public getApplicationsForDrive(id:string){return this.applications.filter(a=>a.driveId===id);}
  public getApplicationsByStudent(id:string){return this.applications.filter(a=>a.studentId.toUpperCase()===id.trim().toUpperCase());}
  public getApplicationsForMentor(mentor:Pick<User,'name'|'email'>){const ids=new Set(studentService.getStudentsForMentor(mentor).map(s=>s.Student_ID.toUpperCase()));return this.applications.filter(a=>ids.has(a.studentId.toUpperCase()));}
  public applyToDrive(student:StudentRecord,drive:PlacementDrive):ActionResult{const live=this.getDriveById(drive.id);if(!live||!live.published||(live.status||'Active')==='Closed')return{success:false,message:'This drive is no longer open for applications.'};if(this.isDeadlinePassed(live))return{success:false,message:`The application deadline (${live.applicationDeadline}) has passed.`};if(this.applications.some(a=>a.studentId.toUpperCase()===student.Student_ID.toUpperCase()&&a.driveId===live.id))return{success:false,message:'You have already submitted an application for this placement drive.'};const elig=this.checkEligibility(student,live);if(!elig.eligible)return{success:false,message:`Eligibility criteria not met: ${elig.reasons.join(', ')}`};const a:any={id:`app-${Date.now()}`,driveId:live.id,studentId:student.Student_ID,studentName:student.Full_Name,companyName:live.companyName,role:live.role,packageLPA:live.packageLPA,appliedDate:new Date().toISOString().split('T')[0],appliedAt:new Date().toISOString(),status:'Applied',stageNotes:'Application received. Awaiting review by the T&P Cell.',resumeFileName:student.ResumeUploaded?student.ResumeFileName:undefined};this.applications.unshift(a);emitDataChange();void apiClient.apply(live.id).then(saved=>{const i=this.applications.findIndex(x=>x.id===a.id);if(i>=0)this.applications[i]=saved;emitDataChange();}).catch(()=>{});return{success:true,message:`Successfully applied to ${live.companyName} for ${live.role}!`};}
  public updateApplicationStatus(id:string,status:ApplicationStatus,notes:string|undefined,actor?:Actor){if(!this.canManage(actor))return false;const a=this.applications.find(x=>x.id===id);if(!a)return false;Object.assign(a,{status,stageNotes:notes||a.stageNotes,updatedAt:new Date().toISOString()});emitDataChange();void apiClient.updateApplication(id,{status,stageNotes:a.stageNotes}).then(saved=>{const i=this.applications.findIndex(x=>x.id===id);if(i>=0)this.applications[i]=saved;emitDataChange();}).catch(()=>{});return true;}
  public deleteApplicationsForStudents(ids:string[]){const set=new Set(ids.map(i=>i.toUpperCase()));const before=this.applications.length;this.applications=this.applications.filter(a=>!set.has(a.studentId.toUpperCase()));emitDataChange();return before-this.applications.length;}
  public getStats(students:StudentRecord[],applications:JobApplication[]=this.applications):PlacementStats{const byStatus:Record<ApplicationStatus,number>={Applied:0,'Under Review':0,Shortlisted:0,Interview:0,Selected:0,Rejected:0};const companies=new Map<string,{applications:number;selected:number}>();applications.forEach(a=>{if(byStatus[a.status]!==undefined)byStatus[a.status]++;const c=companies.get(a.companyName)||{applications:0,selected:0};c.applications++;if(a.status==='Selected')c.selected++;companies.set(a.companyName,c);});return{totalStudents:students.length,totalDrives:this.drives.length,publishedDrives:this.drives.filter(d=>d.published).length,activeDrives:this.drives.filter(d=>d.published&&(d.status||'Active')==='Active').length,totalApplications:applications.length,shortlisted:byStatus.Shortlisted+byStatus.Interview+byStatus.Selected,selected:byStatus.Selected,byStatus,byCompany:Array.from(companies.entries()).map(([company,v])=>({company,...v})).sort((a,b)=>b.applications-a.applications)};}
  public broadcastAnnouncement(title:string,message:string,type:NotificationItem['type']='drive',studentId?:string){const n:any={id:`notif-${Date.now()}`,title,message,type,studentId,read:false,timestamp:new Date().toISOString()};this.notifications.unshift(n);emitDataChange();void apiClient.createNotification(n).then(saved=>{const i=this.notifications.findIndex(x=>x.id===n.id);if(i>=0)this.notifications[i]=saved;emitDataChange();}).catch(()=>{});}
  public getNotificationsForStudent(id:string){const key=id.toUpperCase();return this.notifications.filter(n=>!n.studentId||n.studentId.toUpperCase()===key);}
  public markNotificationAsRead(id:string){const n=this.notifications.find(x=>x.id===id);if(n){n.read=true;emitDataChange();void apiClient.markNotification(id,true).then(saved=>{const i=this.notifications.findIndex(x=>x.id===id);if(i>=0)this.notifications[i]=saved;emitDataChange();}).catch(()=>{});}}
  public exportEligibleStudentsCsv(students:StudentRecord[],drive:PlacementDrive){const headers=['Student_ID','Full_Name','Email','Phone','Branch','CGPA','Backlogs','Attendance_Percentage','Technical_Skills','Projects_Count','Eligibility_Status'];const rows=students.map(s=>{const {eligible,reasons}=this.checkEligibility(s,drive);return[s.Student_ID,`"${s.Full_Name.replace(/"/g,'""')}"`,s.Email,s.Phone||'N/A',`"${s.Branch}"`,s.CGPA.toFixed(2),s.Backlogs,s.Attendance_Percentage,`"${s.Technical_Skills.join('; ')}"`,s.Projects.length,eligible?'ELIGIBLE':`DISQUALIFIED (${reasons.join(' | ')})`].join(',')});return[headers.join(','),...rows].join('\n');}
  public matchCandidatesForRole(allStudents:StudentRecord[],criteria:{minCGPA:number;maxBacklogs:number;branches:string[];requiredSkills:string[]}){return allStudents.map(stu=>{const fail:string[]=[];if(stu.CGPA<criteria.minCGPA)fail.push(`CGPA ${stu.CGPA.toFixed(2)} < ${criteria.minCGPA}`);if(stu.Backlogs>criteria.maxBacklogs)fail.push(`${stu.Backlogs} Backlogs > ${criteria.maxBacklogs}`);if(criteria.branches.length&&!criteria.branches.includes(stu.Branch))fail.push(`Branch ${stu.Branch} not in filter`);const stage1Passed=!fail.length;const skills=stu.Technical_Skills.map(s=>s.toLowerCase());const matchingSkills=criteria.requiredSkills.filter(r=>skills.some(s=>s.includes(r.toLowerCase())||r.toLowerCase().includes(s)));const missingSkills=criteria.requiredSkills.filter(r=>!skills.some(s=>s.includes(r.toLowerCase())||r.toLowerCase().includes(s)));const skillFit=criteria.requiredSkills.length?(matchingSkills.length/criteria.requiredSkills.length)*60:60;const projectBonus=Math.min(20,stu.Projects.length*7);const codingBonus=Math.min(20,(stu.Coding_Activity.problemsSolved/400)*20);const stage2FitScore=Math.min(100,Math.round(skillFit+projectBonus+codingBonus));const readinessScore=Math.min(98,Math.round((stu.CGPA/10)*40+stu.Technical_Skills.length*5+stu.Projects.length*10));return{student:stu,stage1Passed,stage1FailReasons:fail,stage2FitScore,matchingSkills,missingSkills,readinessScore};}).sort((a,b)=>a.stage1Passed===b.stage1Passed?b.stage2FitScore-a.stage2FitScore:a.stage1Passed?-1:1);}
}
export const placementService=new PlacementService();
